language: csharp
dotnet: 3.1
solution: NapierBankMessageFilteringServicee.sln
install:
  - nuget restore ./NapierBankMessageFilteringService/NapierBankMessageFilteringService.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release ./NapierBankMessageFilteringService/NapierBankMessageFilteringService.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./XTests/bin/Release/XTests.dll