language: csharp
mono: none
dotnet: 3.1

script:
  - dotnet --version
  - dotnet restore
  - dotnet build
  - msbuild /p:Configuration=Release ./NapierBankMessageFilteringService/NapierBankMessageFilteringService.sln
  - dotnet test -c Release --no-build test/XTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)