language: csharp
mono: none
solution: NapierBankMessageFilteringServicee.sln
install:
  - nuget restore ./NapierBankMessageFilteringService/NapierBankMessageFilteringService.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - dotnet --version
  - dotnet restore
  - dotnet build
  - msbuild /p:Configuration=Release ./NapierBankMessageFilteringService/NapierBankMessageFilteringService.sln
  - dotnet test -c Release --no-build test/XTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)